# This is a basic workflow to help you get started with Actions

name: Build and Publish Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  jobs:
    push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ericfaris/competition-corner-bot
            
        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            args:
              - --build-arg APPLICATION_ID=${{ secrets.APPLICATION_ID }}
              - --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }}
              - --build-arg COMMANDS_DIR=${{ secrets.COMMANDS_DIR }}
              - --build-arg COMPETITION_CHANNEL_ID=${{ secrets.COMPETITION_CHANNEL_ID }}
              - --build-arg COMPETITION_CHANNEL_NAME=${{ secrets.COMPETITION_CHANNEL_NAME }}
              - --build-arg COMPETITION_WEEKLY_POST_ID=${{ secrets.COMPETITION_WEEKLY_POST_ID }}
              - --build-arg COMPETITION_SEASON_POST_ID=${{ secrets.COMPETITION_SEASON_POST_ID }}
              - --build-arg DISCORD_BASE_API=${{ secrets.DISCORD_BASE_API }}
              - --build-arg GUILD_ID=${{ secrets.GUILD_ID }}
              - --build-arg SECONDS_TO_DELETE_MESSAGE=${{ secrets.SECONDS_TO_DELETE_MESSAGE }}
              - --build-arg TEST_ONLY=${{ secrets.TEST_ONLY }}
              - --build-arg ENVIRONMENT=${{ secrets.ENVIRONMENT }}
